<div id="menu">
	<ul class="menu">

		<li><a href="index.shtml" class="parent"><span>Home</span></a>
			<div><ul>
				<li><a href="history.shtml" class="parent"><span>History</span></a>
				</li>
			</ul></div>
		</li>

		<li><a href="#"><span>For Residents</span></a>
			<div><ul>
			<li><a href="contact.shtml" class="parent"><span>Contact</span></a></li>
			
			<li><a href="meetings.shtml" class="parent"><span>Meetings</span></a></li>

			<li><a href="#" class="parent"><span>Rules &amp; Regulations</span></a>
				<div><ul>
					<li><a href="rules.shtml"><span>General</span></a></li>
					<li><a href="pets.shtml"><span>Pets</span></a></li>
					<li><a href="movepolicy.shtml"><span>Move in / Move out Policy</span></a></li>
					<li><a href="enforcement.shtml"><span>Enforcement Policy</span></a></li>
				</ul></div>
			</li>
			
			<li><a href="services.shtml"><span>Resident Services</span></a></li>
			
			</ul></div>
		</li>

		<li><a href="art.shtml" class="parent"><span>Art Collection</span></a></li>

		<li><a href="local.shtml" class="parent"><span>Local Resources</span></a></li>

	</ul>
</div>